# Site settings
title: Middle Path Development - Blog
email: middlepathdevelopment@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://middlepathdevelopment.com" # the base hostname & protocol for your site
github_username:  bwanicur
linkedin_username: "benwanicur"

# Build settings
markdown: kramdown

permalink: /blog/:title.html

theme: 'jekyll-theme-cayman'

site_tags:
  - consulting
  - project-management
  - web-development
  - ruby
  - postgresql
